#Which ammo is used by each type of gun.
#Reload type supported.
#Format: "pistol, tacz:9mm" â€” this means that all guns of the type pistol will use the 9mm.
#"pistol, $minecraft:gold_nugget" - use $ to make the guns use item as ammo.
#
"Ammo of Gun" = ["pistol, tacz_unidict:pistol", "sniper, tacz_unidict:sniper", "rifle, tacz_unidict:rifle", "shotgun, tacz_unidict:shot", "smg, tacz_unidict:pistol", "rpg, tacz_unidict:barrel", "mg, tacz_unidict:rifle", "fuel, tacz_unidict:fuel_tank"]
#Which guns are not affected by this mod.
"Gun WhiteList" = []
#Guns that use these types of ammo will not be affected by this mod.
"Ammo WhiteList" = []

